trigger:
  branches:
    include:
      - master  # Runs pipeline on push to master

pool:
  vmImage: 'windows-latest'  # Ensures the pipeline runs on a Windows agent

steps:
  - checkout: self  # Clones the repository

  # Step 1: Install ReadyAPI
  - task: PowerShell@2
    displayName: 'Download and Install ReadyAPI'
    inputs:
      targetType: 'inline'
      script: |
        $installerUrl = "https://storage256.blob.core.windows.net/readapi/ReadyAPI-x64-3.58.0_R60870089923SLM.exe?sp=r&st=2025-02-11T08:44:00Z&se=2025-02-27T16:44:00Z&spr=https&sv=2022-11-02&sr=b&sig=B70uSs7tDBWI%2FFvIhWU9Du8F5fRfIP32xrlI3Zi98mM%3D"
        $installerPath = "$(Build.ArtifactStagingDirectory)\ReadyAPI-3.58.0.exe"
        
        # Download ReadyAPI
        Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath

        # Install ReadyAPI silently
        Start-Process -FilePath $installerPath -ArgumentList "/S" -NoNewWindow -Wait

  # Step 2: Verify ReadyAPI Installation
  - task: PowerShell@2
    displayName: 'Verify ReadyAPI Installation'
    inputs:
      targetType: 'inline'
      script: |
        $readyApiPath = "C:\Program Files\SmartBear\ReadyAPI-3.58.0\bin\testrunner.bat"
        if (Test-Path $readyApiPath) {
          Write-Output "ReadyAPI is installed successfully."
        } else {
          Write-Error "ReadyAPI installation failed or not found at expected location."
          exit 1
        }

  # Step 3: Run ReadyAPI Tests
  - task: PowerShell@2
    displayName: 'Run ReadyAPI Tests'
    inputs:
      targetType: 'inline'
      script: |
        $readyApiPath = "C:\Program Files\SmartBear\ReadyAPI-3.58.0\bin\testrunner.bat"
        $projectPath = "$(Build.SourcesDirectory)\REST Project 1-readyapi-project.xml"
        $reportPath = "$(Build.ArtifactStagingDirectory)\reports"

        # Ensure report directory exists
        New-Item -ItemType Directory -Path $reportPath -Force | Out-Null

        # Run the ReadyAPI test
        & "$readyApiPath" -r -a -j -f "$reportPath" -RJUnit -E "Default environment" "$projectPath"

  # Step 4: Publish Test Reports
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Test Reports'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)\reports'
      artifactName: 'TestReports'
